# Generated by Django 5.1.2 on 2024-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_symptom_owner_sintoma_tratamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='frequency',
            field=models.CharField(default='Não especificado', max_length=200),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='description',
            field=models.CharField(default='Não especificado', max_length=200),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='description',
            field=models.CharField(default='Não especificado', max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
