# Generated by Django 5.1.2 on 2024-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_tratamento_frequency_tratamento_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
