# Generated by Django 5.1.2 on 2024-11-07 23:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_tratamento_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='initial_hour',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
